### ISSUE TITLE
Некорректное поведение после повторной инициализации

### ISSUE THREAD

**Issue by antoshalee** [2gis/photor#18]
Инициализируем Photor.new() на DOM-элементе. Проматываем до какого-то слайда. После этого закрываем и выполняем destroy(). После этого снова инициализируем на этом же элементе. 
Результат: видим, что в стилях сохранилось предыдущее положение галереи. Если при повторной инициализации передать данных меньше чем последний активный индекс, то ни одной картиники вообще не отображается.

**Comment by Chaptykov** [comment]
Поправлено в https://github.com/2gis/photor/commit/3f6cfe390abcdaeed9afef290a49d7dfd0ad2f78
