### ISSUE TITLE
На тачевых устройствах не работают клики по элементам

### ISSUE THREAD

**Issue by docentq2** [2gis/photor#20]
В мобильном режиме нельзя обработать клик по элементу внутри фотора. Это было сделано, что бы по двойному тапу он страница не зумилась. Проблема кроется [здесь](https://github.com/2gis/photor/blob/master/dist/photor.js#L942).

Решить как сделать так что бы страница не зумилась, но при этом проходил клик.

**Comment by Chaptykov** [comment]
Уточнение: проблема проявляется для html-слайдов.

**Comment by docentq2** [comment]
Ошибка в старой версии фотора, в версии 2.0 все нормально
