### ISSUE TITLE
Публикация в npm

### ISSUE THREAD

**Issue by Diokuz** [2gis/photor#35]
В фоторе куча картинок, репа весит дофига и когда пытаешься склонить в неудачное время, ничего не получается.

Ещё хуже когда делаешь npm i и он пытается скачать его отсюда.

Было бы круто добавить фотор в npm, и выключить демку из npm пакета.

**Comment by Diokuz** [comment]
like that
```
https://github.com/Diokuz/baron/blob/master/.npmignore
```

**Comment by Chaptykov** [comment]
https://www.npmjs.com/package/photor
