### ISSUE TITLE
Фотор API slidesOnScreen динамическое переключение

### ISSUE THREAD

**Issue by kozhin2012** [2gis/photor#47]
Например я запустил фотор с 3 слайдами на экране.
Можно ли при нажатии на кнопочку сказать фотору чтобы  slidesOnScreen = 1.
Если да то как? У меня не получилось.

**Comment by lastw** [comment]
@kozhin2012 Нет, но ты можешь пересоздать фотор с нужными параметрами.

Пожалуйста, закрой https://github.com/airbnb/react-native-maps/pull/1547 — это не лучший способ привлекать внимание на гитхабе.
